version: "3.8"

services:
  php:
    build: .
    container_name: my_php_rc
    volumes:
      - .:/home
    environment:
      XDEBUG_CONFIG: client_host=host.docker.internal client_port=9003 mode=debug
     